a=input("Enter the recipient: ")
b=input("Enter the message: ")
c=input("Enter the name: ")
d=input("Enter the subject: ")
e=input("Enter the version: ")
f=float(input("Enter the discount: "))
g=input("Enter the status: ")
h=input("Enter the code: ")
i=input("Enter the location: ")
j=int(input("Enter the age: "))
k=input("Enter the company name: ")
l=input("Enter the website: ")
m=input("Enter the phone: ")
n=input("Enter the job title: ")
o=input("Enter the department: ")

print(f"Dear {a}, I hope this email finds you well.")
print(b)
print(f"Subject: {d}")
print(f"Sender: {c}")
print(f"Version: {e")
print(f"Discount: {f:.2f}%")
print(f"Status: {g}")
print(f"Code: {h}")
print(f"Location: {i}")
print(f"Age: {j}")
print(f"Company: {k}")
print(f"Website: {l}")
print(f"Phone: {m}")
print(f"Job Title: {n}")
print(f"Department: {o}")
