cedric=input("Enter the book title: ")
bautista=input("Enter the author: ")
papio=int(input("Enter the year of publication: "))
haha=input("Enter the genre: ")
uu=input("Enter the library: ")
lakas=input("Enter your member ID: ")
lol=input("Enter the return date: ")

print(f"You have successfully reserved the book '{cedric}' by {bautista}.")
print(f"Year of Publication: {papio}")
print(f"Genre: {haha}")
print(f"Library: {uu}")
print(f"Member ID: {lakas}")
print(f"Return Date: {lol}")
