ced=input("Enter Post Date: ")
papi=input("Enter Post Time: ")
papiiced=float(input("Enter Post Reach: "))
cedcedricc=float(input("Enter Post Engagement: "))
chippedego=float(input("Enter Post Duration: "))
kjekkced=input("Enter Post Category: ")
print()
print("Post Scheduled:")
print(f"Date: {ced}")
print(f"Time: {papi}")
print(f"Reach: {papiiced:.2f}")
print(f"Engagement: {cedcedricc:.2f} ")
print(f"Duration: {chippedego:.2f} ")
print(f"Category: {kjekkced}")
